package pdktswdatabase;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pdktswdatabase.Calisan;
import pdktswdatabase.GirisEkrani;
import pdktswdatabase.Kullanıcı;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.

/**
 *
 * @author User
 */
public class PersonelKayit extends javax.swing.JFrame {

    /**
     * Creates new form personelKayit
     */
    public PersonelKayit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        radiokadın = new javax.swing.JRadioButton();
        radioerkek = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txtunvan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtad = new javax.swing.JTextField();
        txtsoyad = new javax.swing.JTextField();
        txtkullanıcıad = new javax.swing.JTextField();
        txtparola = new javax.swing.JTextField();
        txtmaas = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtpass = new javax.swing.JPasswordField();
        txtdogum = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmbGüvenlikSorusu = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtGüvenlikCevap = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("PERSONEL KAYIT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 11, 196, 40));

        jLabel2.setText("Adı");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 100, 108, 22));

        jLabel3.setText("Soyadı");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 140, 108, 21));

        jLabel4.setText("Kullanıcı adı");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 167, 84, 25));

        jLabel5.setText("Şifre");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 195, 58, 23));

        jLabel6.setText("TC Kimlik Numarası");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 236, 108, -1));

        jLabel7.setText("Doğum Tarihi");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 268, 108, -1));

        jLabel8.setText("Cinsiyeti");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 331, 65, -1));

        buttonGroup1.add(radiokadın);
        radiokadın.setText("KADIN");
        getContentPane().add(radiokadın, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 327, -1, -1));

        buttonGroup1.add(radioerkek);
        radioerkek.setText("ERKEK");
        getContentPane().add(radioerkek, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 301, -1, -1));

        jLabel9.setText("Unvanı");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 394, -1, -1));
        getContentPane().add(txtunvan, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 391, 113, -1));

        jLabel10.setText("Maaş");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 432, 46, -1));
        getContentPane().add(txtad, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 101, 120, -1));
        getContentPane().add(txtsoyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 140, 120, -1));
        getContentPane().add(txtkullanıcıad, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 171, 120, -1));
        getContentPane().add(txtparola, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 232, 120, -1));
        getContentPane().add(txtmaas, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 429, 99, -1));

        jButton1.setText("KAYDET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 635, 108, 41));

        jButton2.setText("İPTAL/GERİ DÖN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 635, 128, 41));
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 202, 120, 19));
        getContentPane().add(txtdogum, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 263, 120, -1));

        jLabel11.setText("Personel Id");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jLabel12.setText("Güvenlik Sorusu");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 476, -1, -1));

        cmbGüvenlikSorusu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "İlk Evcil Hayvanınızın Adı ? ", "Annenizin Doğduğu İl ?", "En Sevdiğiniz İlköğretim Hocanız ?", " ", " " }));
        cmbGüvenlikSorusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGüvenlikSorusuActionPerformed(evt);
            }
        });
        getContentPane().add(cmbGüvenlikSorusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 473, -1, -1));

        jLabel13.setText("Güvenlik Sorusu Cevap");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 526, -1, -1));
        getContentPane().add(txtGüvenlikCevap, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 523, 158, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pdktswdatabase/A55.jpg"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 0, -1, -1));

        jLabel15.setText("Sistem tarafından oluşturulacaktır.");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:

            Kullanıcı yenikullanici = new Kullanıcı();
            yenikullanici.id = UUID.randomUUID().hashCode();
            yenikullanici.ad = txtad.getText();
            yenikullanici.kullaniciAdi = txtkullanıcıad.getText();
            yenikullanici.soyad = txtsoyad.getText();
            yenikullanici.unvan = txtunvan.getText();
            yenikullanici.dogumTarihi = txtdogum.getText();
            yenikullanici.maas = Integer.parseInt(txtmaas.getText());
            yenikullanici.sifre = String.valueOf(txtpass.getPassword());
            yenikullanici.cinsiyet = radioerkek.isSelected();
            yenikullanici.tcKimlikNo = txtparola.getText();
            yenikullanici.guvenlikSorusu = cmbGüvenlikSorusu.getSelectedItem().toString();
            yenikullanici.guvenlikCevabi = txtGüvenlikCevap.getText();
              int Maas = Integer.parseInt(txtmaas.getText());
       
           if(Maas<0){
               JOptionPane.showMessageDialog(this, "HATA:Yanlış maaş değeri girdiniz.Tekrar kaydetmeyi deneyiniz");
                PersonelKayit kayit=new PersonelKayit();
                this.dispose();
                kayit.setVisible(true);
                return;
           }

            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/PDKSwDatabase", "sa", "as");
            ///kullanıcı adı varmı
            String query = "SELECT KULLANICIADI FROM PERSONEL WHERE KULLANICIADI='" + yenikullanici.kullaniciAdi + "'";
            Statement stm1 = con.createStatement();
            ResultSet personeller = stm1.executeQuery(query);
            if (personeller.next()) {
                JOptionPane.showMessageDialog(rootPane, yenikullanici.kullaniciAdi + " kullanıcısı  bulunmaktadır");
                return;
            }

//            query = "INSERT INTO PERSONEL (ID,KULLANICIADI,AD,SOYAD,ŞİFRE,CİNSİYET) VALUES(?,?,?,?,?,?,?,?,?)";
            String query2 = "INSERT INTO PERSONEL (ID,AD,SOYAD,KULLANICIADI,UNVAN,TCKİMLİKNO,DOĞUMTARİHİ,CİNSİYET,SIFRE,GUVENLIKSORUSU,GUVENLIKCEVAP,MAAS) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement stm2 = con.prepareStatement(query2);

            stm2.setInt(1, yenikullanici.id);
            stm2.setString(2, yenikullanici.ad);
            stm2.setString(3, yenikullanici.soyad);
            stm2.setString(4, yenikullanici.kullaniciAdi);
            stm2.setString(5, yenikullanici.unvan);
            stm2.setString(6, yenikullanici.tcKimlikNo);
            stm2.setString(7, yenikullanici.dogumTarihi);
            stm2.setInt(12, yenikullanici.maas);
            stm2.setBoolean(8, yenikullanici.cinsiyet);
            stm2.setString(10, yenikullanici.guvenlikSorusu);
            stm2.setString(11, yenikullanici.guvenlikCevabi);
            stm2.setString(9, yenikullanici.sifre);
            stm2.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "KAYIT BAŞARILI");
            GirisEkrani log = new GirisEkrani();
            log.setVisible(true);
            this.dispose();

        } catch (SQLException ex) {
            Logger.getLogger(PersonelKayit.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        GirisEkrani calısanEkranı = new GirisEkrani();
        calısanEkranı.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbGüvenlikSorusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGüvenlikSorusuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGüvenlikSorusuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonelKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonelKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonelKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonelKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonelKayit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmbGüvenlikSorusu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton radioerkek;
    private javax.swing.JRadioButton radiokadın;
    private javax.swing.JTextField txtGüvenlikCevap;
    private javax.swing.JTextField txtad;
    private javax.swing.JTextField txtdogum;
    private javax.swing.JTextField txtkullanıcıad;
    private javax.swing.JTextField txtmaas;
    private javax.swing.JTextField txtparola;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtsoyad;
    private javax.swing.JTextField txtunvan;
    // End of variables declaration//GEN-END:variables
}
