/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pdktswdatabase;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class YoneticiKayit extends javax.swing.JFrame {

    /**
     * Creates new form YoneticiKayit
     */
    public YoneticiKayit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        radiokadın = new javax.swing.JRadioButton();
        radioerkek = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnkaydet = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtad = new javax.swing.JTextField();
        txtsoyad = new javax.swing.JTextField();
        txtkullanıcıad = new javax.swing.JTextField();
        txttc = new javax.swing.JTextField();
        txtdogumtarihi = new javax.swing.JTextField();
        txtunvan = new javax.swing.JTextField();
        txtmaas = new javax.swing.JTextField();
        txtşifre = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbmCombobox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtcevap = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("YÖNETİCİ KAYIT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 29, 248, 32));

        jLabel2.setText("Yönetici ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 79, -1, -1));

        jLabel3.setText("Adı");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 107, 51, -1));

        jLabel4.setText("Soyadı");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 145, 43, -1));

        jLabel5.setText("Kullanıcı Adı");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 195, 60, -1));

        jLabel6.setText("Şifre");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 233, 69, -1));

        jLabel7.setText("TC Kimlik Numarası ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 271, 100, -1));

        jLabel8.setText("Doğum Tarihi");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 309, -1, -1));

        jLabel9.setText("Cinsiyet");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 348, 62, -1));

        buttonGroup1.add(radiokadın);
        radiokadın.setText("KADIN");
        getContentPane().add(radiokadın, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 344, -1, -1));

        buttonGroup1.add(radioerkek);
        radioerkek.setText("ERKEK");
        getContentPane().add(radioerkek, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 385, -1, -1));

        jLabel10.setText("Unvanı");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 448, -1, -1));

        jLabel11.setText("Maaş");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 489, -1, -1));

        btnkaydet.setText("KAYDET");
        btnkaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkaydetActionPerformed(evt);
            }
        });
        getContentPane().add(btnkaydet, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 637, 92, 41));

        jButton1.setText("İPTAL/GERİ DÖN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 637, -1, 41));
        getContentPane().add(txtad, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 104, 114, -1));
        getContentPane().add(txtsoyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 142, 114, -1));
        getContentPane().add(txtkullanıcıad, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 192, 114, -1));
        getContentPane().add(txttc, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 268, 114, -1));
        getContentPane().add(txtdogumtarihi, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 306, 114, -1));
        getContentPane().add(txtunvan, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 445, 113, -1));
        getContentPane().add(txtmaas, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 486, 113, -1));
        getContentPane().add(txtşifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 230, 114, -1));

        jLabel12.setText("Sistem tarafından oluşturulacaktır.");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 79, -1, -1));

        jLabel13.setText("Güvenlik sorusu");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 535, 113, -1));

        cbmCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En sevdiğiniz ders?", "İlk evcil hayvanınız?", "İlk arabanızın modeli?" }));
        getContentPane().add(cbmCombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 532, -1, -1));

        jLabel14.setText("Güvenlik sorusu cevabı:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 573, -1, -1));
        getContentPane().add(txtcevap, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 570, 134, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pdktswdatabase/1234.jpg"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnkaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkaydetActionPerformed
        // TODO add your handling code here:
            try {
            // TODO add your handling code here:

            Kullanıcı yenikullanici = new Kullanıcı();
            yenikullanici.id = UUID.randomUUID().hashCode();
            yenikullanici.ad = txtad.getText();
            yenikullanici.kullaniciAdi = txtkullanıcıad.getText();
            yenikullanici.soyad = txtsoyad.getText();
            yenikullanici.unvan = txtunvan.getText();
            yenikullanici.dogumTarihi = txtdogumtarihi.getText();
            yenikullanici.maas = Integer.parseInt(txtmaas.getText());
            yenikullanici.sifre = String.valueOf(txtşifre.getPassword());
            yenikullanici.cinsiyet = radioerkek.isSelected();
            yenikullanici.tcKimlikNo = txttc.getText();
            yenikullanici.guvenlikSorusu = cbmCombobox.getSelectedItem().toString();
            yenikullanici.guvenlikCevabi = txtcevap.getText();
  int Maas = Integer.parseInt(txtmaas.getText());
       
           if(Maas<0){
               JOptionPane.showMessageDialog(this, "HATA:Yanlış maaş değeri girdiniz.Tekrar kaydetmeyi deneyiniz");
                PersonelKayit kayit=new PersonelKayit();
                this.dispose();
                kayit.setVisible(true);
                return;
           }
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/PDKSwDatabase", "sa", "as");
            ///kullanıcı adı varmı
            String query = "SELECT KULLANICIADI FROM YONETICI WHERE KULLANICIADI='" + yenikullanici.kullaniciAdi + "'";
            Statement stm1 = con.createStatement();
            ResultSet personeller = stm1.executeQuery(query);
            if (personeller.next()) {
                JOptionPane.showMessageDialog(rootPane, yenikullanici.kullaniciAdi + " kullanıcısı  bulunmaktadır");
                return;
            }

//            query = "INSERT INTO PERSONEL (ID,KULLANICIADI,AD,SOYAD,ŞİFRE,CİNSİYET) VALUES(?,?,?,?,?,?,?,?,?)";
            String query2 = "INSERT INTO YONETICI (ID,AD,SOYAD,KULLANICIADI,UNVAN,TCKİMLİKNO,DOĞUMTARİHİ,CİNSİYET,SIFRE,GUVENLIKSORUSU,GUVENLIKCEVAP,MAAS) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement stm2 = con.prepareStatement(query2);

            stm2.setInt(1, yenikullanici.id);
            stm2.setString(2, yenikullanici.ad);
            stm2.setString(3, yenikullanici.soyad);
            stm2.setString(4, yenikullanici.kullaniciAdi);
            stm2.setString(5, yenikullanici.unvan);
            stm2.setString(6, yenikullanici.tcKimlikNo);
            stm2.setString(7, yenikullanici.dogumTarihi);
            stm2.setInt(12, yenikullanici.maas);
            stm2.setBoolean(8, yenikullanici.cinsiyet);
            stm2.setString(10, yenikullanici.guvenlikSorusu);
            stm2.setString(11, yenikullanici.guvenlikCevabi);
            stm2.setString(9, yenikullanici.sifre);
            stm2.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "KAYIT BAŞARILI");
            GirisEkrani log = new GirisEkrani();
            log.setVisible(true);
            this.dispose();

        } catch (SQLException ex) {
            Logger.getLogger(PersonelKayit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnkaydetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GirisEkrani calısanEkranı = new GirisEkrani();
        calısanEkranı.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YoneticiKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YoneticiKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YoneticiKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YoneticiKayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YoneticiKayit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnkaydet;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbmCombobox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton radioerkek;
    private javax.swing.JRadioButton radiokadın;
    private javax.swing.JTextField txtad;
    private javax.swing.JTextField txtcevap;
    private javax.swing.JTextField txtdogumtarihi;
    private javax.swing.JTextField txtkullanıcıad;
    private javax.swing.JTextField txtmaas;
    private javax.swing.JTextField txtsoyad;
    private javax.swing.JTextField txttc;
    private javax.swing.JTextField txtunvan;
    private javax.swing.JPasswordField txtşifre;
    // End of variables declaration//GEN-END:variables
}
